### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ggraziotti** [home-assistant/hassio-installer#43]
With the command on raspberry3 with raspbian ontano the error:

curl -sL https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh | bash -s -- -m raspberry3

I execute has root user

Error:

"No networkmanager support on host"
Can someone help me ?

**Comment by tanasegabriel** [comment]
This was made mandatory in https://github.com/home-assistant/hassio-installer/pull/36, but I'm not sure why, a PR description would have been handy in here.

Either way, I rebuilt my Pi based swarm cluster and Raspbian Buster doesn't come with network-manager. I don't see any value in migrating to it just for running Hassio, so I downloaded the installer script and commented out [line #23](https://github.com/home-assistant/hassio-installer/blob/3f47e87463518b4849c41b9d555a8d2baa13e51d/hassio_install.sh#L23) (previously it didn't also mean exiting with a non-zero status code and again, I've no idea why it should do that now) and everything seems to be working for me so far.

Maybe I'm missing something obvious here when it comes to this hard dependency, maybe @pvizeli can shed some light.

**Comment by frenck** [comment]
You need to install the NetworkManager dependency, package: `network-manager`.
For more information and details, check out our documentation: <https://www.home-assistant.io/hassio/installation/#alternative-install-on-a-generic-linux-host>

**Comment by tanasegabriel** [comment]
That makes sense @frenck. Question is - should this be mandatory? In my opinion, this should be mandatory if the whole system would not work because of it.

I've been running Hassio for a couple of years without `network-manager` and I just re-installed it yesterday while overriding this.

What's the actual side-effect of not using it, provided that you have static IPs and static DNS servers (I bet this is the case for most of the Hassio users). I'm OK with submitting a PR for adding an argument used to skip this check if you accept this approach.

**Comment by pvizeli** [comment]
Feel free to contribute the dbus support for systemd-networkd (I think your system will use this, if you not relay on NM).

We start to support WLAN/Network setup over UI and I implement this for network-manager but I'm not block contribution for other backends with dbus support like systemd-networkd.

**Comment by pvizeli** [comment]
the offer is still open, but I revert the networkmanager
