### ISSUE TITLE
Installer fails on raspberry pi 4

### ISSUE THREAD

**Issue by surak** [home-assistant/hassio-installer#49]
```
curl -sL https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh | sudo bash -s -- -m raspberrypi4 -p /opt
[Warning] No NetworkManager support on host.
[Warning] No AppArmor support on host.
[Info] Install supervisor Docker container
[Info] Install supervisor startup scripts
bash: line 142: /opt/sbin/hassio-supervisor: No such file or directory
```

**Comment by ChrisHaPunkt** [comment]
The curl command on this line (142) tries to download to /opt/sbin/ on your raspian-filesystem, wich not exist.
Try to let the -p and -s flag untouched and only provide the -d flag for data-mountpoint for correct raspian integration

**Comment by surak** [comment]
Plus, the machine name is wrong on the installer. If -m is left alone, it suggests you armv7l (which will fail) - while the correct is raspberrypi4

**Comment by laurent-martin** [comment]
I had a problem using the installer because I specified -m armv7l because of a misunderstanding of the error message when no -m option is given:
see: https://community.home-assistant.io/t/145697
Error message was:
```
[ERROR] Please set machine for armv7l
```
I erroneously used -m armv7l   instead of  -m raspberrypi3
And that created a difficult to recover problem... (basically needed to cleanup all docker).
My suggestion if to make this request in the script:
```
DOCKER_REPO=homeassistant
curl -s https://hub.docker.com/v2/repositories/$DOCKER_REPO/?page_size=1000| jq -r '.results|.[]|.name'|sed -ne 's/-homeassistant$//p'|sort
```
This lists all currently supported architectures for homeassistant in hassio
Based on that:
1- check that image exists if user specifies -m
2- if no -m, propose the list after the error message
