### ISSUE TITLE
 "Please install Avahi first" Issue #87 from hassio-build repo

### ISSUE THREAD

**Issue by Bodge-IT** [home-assistant/hassio-installer#69]
Hi, I'm getting the same issue as https://github.com/home-assistant/hassio-build/issues/87 I'm using machine build qemux86-64 on a debian **edit: buster(not stretchy)** install.  All install steps were taken from https://www.home-assistant.io/hassio/installation/#alternative-install-on-a-generic-linux-host
```
[Error] Please install avahi first
```
I tried as logged in user and as su

I can confirm Avahi-daemon IS installed:
```
bw-admin@animus:~$ sudo apt-get install avahi-daemon
Reading package lists... Done
Building dependency tree
Reading state information... Done
avahi-daemon is already the newest version (0.7-4+b1).
```
and:
```
#bw-admin@animus:~$ sudo systemctl status avahi-daemon.service                                                             avahi-daemon.service - Avahi mDNS/DNS-SD Stack
   Loaded: loaded (/lib/systemd/system/avahi-daemon.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-01-15 07:51:14 GMT; 1 day 1h ago
 Main PID: 1891 (avahi-daemon)
   Status: "avahi-daemon 0.7 starting up."
    Tasks: 2 (limit: 4915)
   Memory: 1.1M
   CGroup: /system.slice/avahi-daemon.service
           ├─1891 avahi-daemon: running [animus-2.local]
           └─1892 avahi-daemon: chroot helper
```

**Comment by Bodge-IT** [comment]
I think there may be something inconsistent with the script and/or install docs?

**Comment by pvizeli** [comment]
Is that called the same overall?

**Comment by Bodge-IT** [comment]
"Is that called the same overall?"
Sorry @pvizeli , not sure what you mean?

**Comment by Bodge-IT** [comment]
**update** sorry, not stretchy install, is a buster install.

**Comment by Bodge-IT** [comment]
I can confirm changing the status check as above, worked for me on Buster.

**Comment by viktak** [comment]
I have the same problem on a clean Debian 10 installation.

`dev@debian:~$ sudo systemctl status avahi-daemon.service
● avahi-daemon.service - Avahi mDNS/DNS-SD Stack
   Loaded: loaded (/lib/systemd/system/avahi-daemon.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-01-27 15:25:00 EET; 10min ago
 Main PID: 343 (avahi-daemon)
   Status: "avahi-daemon 0.7 starting up."
    Tasks: 2 (limit: 2043)
   Memory: 1.6M
   CGroup: /system.slice/avahi-daemon.service
           ├─343 avahi-daemon: running [debian.local]
           └─358 avahi-daemon: chroot helper

Jan 27 15:25:00 debian avahi-daemon[343]: Server startup complete. Host name is debian.local. Local service cookie is 149964884.
Jan 27 15:25:07 debian avahi-daemon[343]: Joining mDNS multicast group on interface enp3s0.IPv6 with address fe80::226:2dff:fe15:ed23.
Jan 27 15:25:07 debian avahi-daemon[343]: New relevant interface enp3s0.IPv6 for mDNS.
Jan 27 15:25:07 debian avahi-daemon[343]: Registering new address record for fe80::226:2dff:fe15:ed23 on enp3s0.*.
Jan 27 15:25:07 debian avahi-daemon[343]: Joining mDNS multicast group on interface enp3s0.IPv4 with address 192.168.1.112.
Jan 27 15:25:07 debian avahi-daemon[343]: New relevant interface enp3s0.IPv4 for mDNS.
Jan 27 15:25:07 debian avahi-daemon[343]: Registering new address record for 192.168.1.112 on enp3s0.IPv4.
Jan 27 15:25:11 debian avahi-daemon[343]: Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.0.1.
Jan 27 15:25:11 debian avahi-daemon[343]: New relevant interface docker0.IPv4 for mDNS.
Jan 27 15:25:11 debian avahi-daemon[343]: Registering new address record for 172.17.0.1 on docker0.IPv4.`

`systemctl is-active --quiet avahi-daemon` returns nothing.

**Comment by Bodge-IT** [comment]
systemctl is-active --quiet avahi-daemon returns nothing. in Bash yes but when run through the script, the installer works.  I forked this repo to my own Github and modified the installer.  Then changed the curl to reflect the new location adding my own params to the request.

**Comment by viktak** [comment]
Yes, you are right, it worked, thank you for your help!

**Comment by pvizeli** [comment]
I close the issue. Look like no one will work on it and provide a fix for many Linux.

**Comment by chernyshaw** [comment]
`sudo curl -sL "https://raw.githubusercontent.com/home-assistant/supervised-installer/master/installer.sh" | sudo bash -s -- -m qemux86-64`
Add couple of sudo and it finally works for me!
